/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import java.io.FileOutputStream;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;
import com.sun.scenario.effect.ImageData;
import java.io.Writer;
import javax.swing.JOptionPane;

/**
 *
 * @author Anadah Musah
 */
public class Reports {

    private Object ImageDataFactory;
    ImageData data;
    private Object pdfWriter;

    public void generate() {
        PdfPCell table_cell;
        try {
            PdfWriter writer;
            /* Step-2: Initialize PDF documents - logical objects */
            Document my_pdf_report = new Document();
            PdfWriter.getInstance(my_pdf_report, new FileOutputStream("Report.pdf"));

           // Writer.setPageEvent(new PDFEventListener());
            my_pdf_report.open();

            //we have four columns in our table
            PdfPTable my_report_table = new PdfPTable(3);
            PdfPTable my_header_table = new PdfPTable(3);
            //create a cell object
            class MyFooter extends PdfPageEventHelper {

                Font ffont = new Font(Font.FontFamily.UNDEFINED, 6, Font.ITALIC);

                @Override
                public void onEndPage(PdfWriter writer, Document document) {
                    PdfContentByte cb = writer.getDirectContent();
                    Phrase footer = new Phrase("Report card designed and generated by Shazka Systems.", ffont);

                    ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                            footer,
                            (document.right() - document.left()) / 2 + document.leftMargin(),
                            document.bottom() - 10, 0);
                }
            }
            //header table

            //adding an image
            Image image = Image.getInstance("images/logo.png");
            image.setAlignment(Element.ALIGN_CENTER);
            image.setBorderColor(BaseColor.BLUE);
            image.scaleAbsolute(100, 100);
            image.setBorder(3);
            image.setWidthPercentage(56);

            //image 2
            Image image2 = Image.getInstance("images/java.png");
            image2.setAlignment(Element.ALIGN_CENTER);
            image2.setBorderColor(BaseColor.BLUE);

            Paragraph titl = new Paragraph("Kisii University", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Font.BOLD, BaseColor.BLUE));
            titl.setAlignment(Element.ALIGN_CENTER);
            my_pdf_report.add(image);
            my_pdf_report.add(titl);

            Paragraph titl1 = new Paragraph("Applied Computer Science", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Font.BOLD, BaseColor.BLUE));
            titl1.setAlignment(Element.ALIGN_CENTER);
            my_pdf_report.add(titl1);

            Paragraph titl2 = new Paragraph("P.O BOX 408-40200", FontFactory.getFont(FontFactory.HELVETICA, 18, Font.BOLD, BaseColor.BLUE));
            titl2.setAlignment(Element.ALIGN_CENTER);
            my_pdf_report.add(titl2);
            Paragraph titl3 = new Paragraph("Kisii", FontFactory.getFont(FontFactory.HELVETICA, 18, Font.BOLD, BaseColor.BLUE));
            titl3.setAlignment(Element.ALIGN_CENTER);
            my_pdf_report.add(titl3);
            Paragraph titl4 = new Paragraph("*************************************", FontFactory.getFont(FontFactory.HELVETICA, 18, Font.BOLD, BaseColor.RED));
            titl4.setAlignment(Element.ALIGN_CENTER);
            my_pdf_report.add(titl4);

//            //header
//           table_cell=new PdfPCell(new Chunk(image,3,3));
//            my_header_table.addCell(table_cell);
//            my_header_table.addCell("Kisii university Applied computer science Y3S2");
//            my_header_table.addCell(image2);
            //table
            String t1 = "Name";
            table_cell = new PdfPCell(new Phrase(t1, FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
            //table_cell.setColspan(6);
            table_cell.setBackgroundColor(BaseColor.PINK);
            table_cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            my_report_table.addCell(table_cell);

            String t2 = "Phone";
            table_cell = new PdfPCell(new Phrase(t2, FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
            table_cell.setBackgroundColor(BaseColor.PINK);
            table_cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            my_report_table.addCell(table_cell);

            String t3 = "Email";
            table_cell = new PdfPCell(new Phrase(t3, FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
            table_cell.setBackgroundColor(BaseColor.PINK);
            table_cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            my_report_table.addCell(table_cell);

            //fetch data from the database
            connect conni = new connect();
            conni.connectdb();

            String sql = "SELECT * FROM phonebook";
            conni.st = conni.conn.createStatement();
            conni.rs = conni.st.executeQuery(sql);
            while (conni.rs.next()) {

                String name = conni.rs.getString("name");
                table_cell = new PdfPCell(new Phrase(name));
                table_cell.setBackgroundColor(BaseColor.GRAY);
                table_cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                my_report_table.addCell(table_cell);

                String phone = conni.rs.getString("phone");
                table_cell = new PdfPCell(new Phrase(phone));
                table_cell.setBackgroundColor(BaseColor.GRAY);
                table_cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                my_report_table.addCell(table_cell);
                String email = conni.rs.getString("email");
                table_cell = new PdfPCell(new Phrase(email));
                table_cell.setBackgroundColor(BaseColor.GRAY);
                table_cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                my_report_table.addCell(table_cell);
            }

            my_pdf_report.add(my_report_table);

            conni.conn.close();
            my_pdf_report.close();
            my_pdf_report.open();
            JOptionPane.showMessageDialog(null, "Report saved");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public class PDFEventListener extends PdfPageEventHelper {

        @Override

        public void onEndPage(PdfWriter writer, Document document) {

            PdfContentByte canvas = writer.getDirectContentUnder();

            Phrase watermark = new Phrase("GATHUKU REPORTS", new Font(Font.FontFamily.TIMES_ROMAN, 190, Font.NORMAL, BaseColor.LIGHT_GRAY));

            ColumnText.showTextAligned(canvas, Element.ALIGN_CENTER, watermark, 337, 500, 45);

        }

    }
}
